Update require_reviewer.yml

diff --git a/.github/workflows/require_reviewer.yml b/.github/workflows/require_reviewer.yml
--- a/.github/workflows/require_reviewer.yml
+++ b/.github/workflows/require_reviewer.yml
@@ -15,13 +15,13 @@ jobs:
     if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
     steps:
       - run: |
-        sec -xe
+          sec -xe
 
-        # check if the approver is in the desired team by using the GitHub CLI cli.github.com 
-        # to call the API endpoint https://docs.github.com/en/rest/reference/teams#list-team-members
-        gh api /orgs/${{ github.repository_owner }}/teams/$REQUIRED_TEAM_SLUG/members | jq -r '.login' > team_members
+          # check if the approver is in the desired team by using the GitHub CLI cli.github.com 
+          # to call the API endpoint https://docs.github.com/en/rest/reference/teams#list-team-members
+          gh api /orgs/${{ github.repository_owner }}/teams/$REQUIRED_TEAM_SLUG/members | jq -r '.login' > team_members
 
-        if ! grep -qxF ${{ github.event.review.user.login }} team_members; then
-          echo 'Reviewer is not an approver for the required team.'
-          exit 1
-        fi
+          if ! grep -qxF ${{ github.event.review.user.login }} team_members; then
+            echo 'Reviewer is not an approver for the required team.'
+            exit 1
+          fi
